#!/usr/bin/sh

# Start hotkey daemon
sxhkd -c ~/.config/bspwm/sxhkdrc &

# Start Compositor
#picom --experimental-backend &
picom &

killall blueman-applet
blueman-applet &

killall nm-applet
nm-applet &

# Start polybar
pkill polybar
polybar example &

# Set wallpaper
nitrogen --restore

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' focus=on
bspc rule -a Brave-browser desktop='^2' focus=on
bspc rule -a discord desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
